SELECT NOMBRE
FROM EMPLEADO
WHERE ALOJAMIENTO>(SELECT max(NUMALOJ)
                        FROM ALOJAMIENTO
                        WHERE ALOJAMIENTO IN ('MULLERS','PAPA KING'))
                        
/*
SELECT NOMBRE
FROM EMPLEADO
WHERE ALOJAMIENTO>ALL(SELECT NUMALOJ
FROM ALOJAMIENTO

WHERE ALOJAMIENTO IN ('MULLERS','PAPA KING'))
*/
                        



