DECLARE
    P_E EMPLEADOPRUEBA%ROWTYPE;
    V_BOOLEAN BOOLEAN;
BEGIN
    /*
    SELECT * INTO P_E FROM EMPLEADOPRUEBA E
    WHERE  E.NUMEMP = 1;
    P_E.NOMBRE := 'KKDVK';
    P_E.NUMEMP := 20; 
    PAQUETEEMPLEADO.PEADD(P_E);
    */
    
    /*
    P_E := PAQUETEEMPLEADO.PEGET(20);
    DBMS_OUTPUT.PUT_LINE(P_E.NUMEMP);
    */
    /*
    SELECT * INTO P_E FROM EMPLEADOPRUEBA E
    WHERE  E.NUMEMP = 20;
    P_E.NOMBRE := 'NOMBREDEPESET';
    V_BOOLEAN := PAQUETEEMPLEADO.PESET(P_E);
    IF V_BOOLEAN THEN
        DBMS_OUTPUT.PUT_LINE('CONSEGUIDO');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('FALLADO');
    END IF;
    */
    /* 
    SELECT * INTO P_E FROM EMPLEADOPRUEBA E
    WHERE  E.NUMEMP = 20;
    V_BOOLEAN := PAQUETEEMPLEADO.PEDELETE(P_E);
      IF V_BOOLEAN THEN
        DBMS_OUTPUT.PUT_LINE('CONSEGUIDO');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('FALLADO');
    END IF;
    */
    COMMIT;
END;